### ISSUE TITLE
[BUG] 在 ide-electron 中，使用antd的Select组件，选择后没有关闭下拉

### ISSUE THREAD

**Issue by HaiBoWon** [opensumi/core#4048]
**描述你的问题（Describe the bug）**

使用antd4.x的Select组件，选择后没有自动关闭下拉

<img width="161" alt="image" src="https://github.com/user-attachments/assets/7cbd5a65-4d8c-4872-ba1c-ebfe905c69a9">

**Comment by erha19** [comment]
之前排查过相应问题，好像是 antd 内的一个组件消失样式没处理好，你试下加一下：
```less
.sumi_antd-slide-up-leave {
    display: none;
 }
```
